version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/easyinstall
hooks:
  BeforeInstall:
    - location: deploy/preinstall.sh
      timeout: 300
  AfterInstall:
    - location: deploy/postinstall.sh
      timeout: 300
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 60
